contractortracker/contractortracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

contractortracker/main_app/urls.py
from django.urls import path
from main_app import views

urlpatterns = [
    path('', views.home, name='home'),
    path('clients/', views.client_index, name='index'),
    path('clients/new/', views.NewClient.as_view(), name='new_client'),
    path('clients/<int:client_id>/manage', views.manage_client, name='manage_client'),
    path('clients/<int:client_id>/manage/description/', views.add_task, name='add_task'),
    path('accounts/signup/', views.signup, name='signup'),
    # path('accounts/signup/', views.SignUpForm.as_view(), name='signup'),

]

contractortracker/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.



class Client(models.Model):
    name = models.CharField(
        "Client Name",
        max_length=30)
    address1 = models.CharField(
        "Address line 1",
        max_length=100,
    )

    address2 = models.CharField(
        "Address line 2",
        max_length=100,
        blank=True
    )

    zip_code = models.CharField(
        "ZIP / Postal code",
        max_length=12,
    )

    city = models.CharField(
        "City",
        max_length=100,
    )
    state = models.CharField(
        "State",
        max_length=2,
    )

    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    new_line = '\n'
    def __str__(self):
        return f"{self.name}{self.address1}{self.new_line}{self.address2}{self.city}, {self.state} {self.zip_code}"
    created_time = models.DateTimeField('date created', default=timezone.now)

class Task(models.Model):
    description = models.TextField(max_length=2048)
    complete = models.BooleanField(default=False)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        if len(self.description) > 15:
            return f"{self.description[:15]}..."
        else:
            return f"{self.description}"

contractortracker/main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task
from django.contrib.auth.forms import UserCreationForm 
from django.forms.fields import EmailField  
from django.contrib.auth.models import User  
from django.core.exceptions import ValidationError



class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['description']

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='username', min_length=5, max_length=150)
    email = forms.EmailField(label='email')
    first_name = forms.CharField(label='first name', min_length=2, max_length=30)
    last_name = forms.CharField(label='first name', min_length=2, max_length=30)
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    license_number = forms.CharField(label='License Number', widget=forms.NumberInput)

    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError(" Email Already Exists")  
        return email  

    def license_clean(self):
        license_number = self.cleaned_data['license_number'].lower()
        new = User.objects.filter(license_number=license_number)
        if new.count():
            raise ValidationError("License number already in use, please contact admin")
        return license_number
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Passwords don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user  

contractortracker/main_app/views.py
from django.shortcuts import render
from re import template
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Client, Task
from .forms import TaskForm, CustomUserCreationForm

# Create your views here.
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            print(form)
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid signup. Please try again. Sorry!'

    form = CustomUserCreationForm()
    context = {
        'form': form,
        'error_message': error_message
    }
    return render(request, 'registration/signup.html', context)

def client_index(request):
    clients = Client.objects.all
    return render(request, 'clients/index.html', {'clients': clients})

def home(request):
    return render(request, "home.html")

# def signup(request):
#     error_message = ''
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('index')
#         else:
#             error_message = 'Invalid signup. Sorry!!! Try again.'
#     form = UserCreationForm()
#     context = {
#         'form': form,
#         'error_message': error_message
#     }
#     return render (request, 'registration/signup.html', context)

class NewClient(LoginRequiredMixin, CreateView):
    model = Client
    fields = ['name', 'address1', 'address2', 'city', 'state', 'zip_code']
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('index')

def manage_client(request, client_id):
    client = Client.objects.get(id=client_id)
    return render(request, 'clients/manage.html', {'client': client})

def add_task(request, client_id):
    form = TaskForm(request.POST)
    client = Client.objects.get(id=client_id)
    if form.is_valid():
        new_task = form.save(commit=False)
        new_task.client_id = client.id
        new_task.completed = True
        # this is where new_recipe.user = request.user would be for pourspot
        new_task.save()
        client = Client.objects.get(id=client_id)
        return render(request, 'clients/manage.html', {'client': client})
    return render(request, 'main_app/task_form.html', {'form': form, 'client': client})

contractortracker/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>contractor tracker home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
<header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <ul class="right">
                <!-- changes below -->
                {% if user.is_authenticated %}
                    <li><a href="{% url 'index' %}">View All Clients</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
<footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; Francis Gacad &nbsp;</div>
</footer>
</body>
</html>

contractortracker/main_app/templates/clients/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Here is a list of your current clients</h1>
    <a href="{% url 'new_client' %}">set up new client</a>
    {%if clients.count%}
    {%for client in clients%}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{client.name}}</span>
            <p>
            {{client.address1}}
            {%if client.address2.count%}
            <br />
            {{client.address2}}
            {% endif %}
            <br />
            {{client.city}}, {{client.state}} {{client.zip_code}}
            </p>
        </div>
        <div class="card-action">
            <div class="complete-or-delete">
            <a class="btn-small red lighten-2" href="{% url 'manage_client' client.id%}">manage</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {%endif%}
{% endblock %}

contractortracker/main_app/templates/clients/manage.html
{% extends 'base.html' %}
{% block content %}
    <h1>Manage Client: {{client.name}}</h1>
    <h5>Description of work:</h5>

        {%for task in client.task_set.all %}
            {{task.description}}
            <br />
        {% endfor %}
        
    <a class="btn-small red lighten-2" href="{% url 'add_task' client.id %}">add work description</a>
{% endblock %}

contractortracker/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome!</h1>
{% endblock %}

contractortracker/main_app/templates/main_app/client_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>New client</h1>
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
    <script>
        {% comment %} const amountSelect = document.getElementById('id_amount'); {% endcomment %}
        {% comment %} M.FormSelect.init(amountSelect); {% endcomment %}
    </script>
{% endblock %}

contractortracker/main_app/templates/main_app/task_form.html
{% extends 'base.html' %}
{% block content %}
  <h1>New work description for {{client.name}}</h1>
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn waves-effect waves-light #29A69A">
  </form>
    

{% endblock %}